### ISSUE TITLE
Prequels

### ISSUE THREAD

**Issue by mjb24v** [Scottjhollywood/WAS_Test#1]
You have made some errors in your app. Screenshot:

![image](https://user-images.githubusercontent.com/20366189/118233860-710b8900-b48a-11eb-846f-159eb746dbb0.png)

**Comment by Scottjhollywood** [comment]
Apologies, I have looked over this "error" for hours and have not seen any issues with it. If you are referring to the quotation I can assure you my source are legitimate. The only potential error is the lack of Harvard referencing in the article, I will aim to rectify this in future endeavours.
